package com.sun.tools.javac.util;

public enum OptionName {
    G, G_NONE, XLINT, XLINT_CUSTOM, NOWARN, VERBOSE, DEPRECATION,
    CLASSPATH, CP, SOURCEPATH, BOOTCLASSPATH, XBOOTCLASSPATH_PREPEND, XBOOTCLASSPATH_APPEND,
    XBOOTCLASSPATH, EXTDIRS, DJAVA_EXT_DIRS, ENDORSEDDIRS, DJAVA_ENDORSED_DIRS,
    PROC, PROCESSOR, PROCESSORPATH, D, S, IMPLICIT, ENCODING, SOURCE, TARGET,
    VERSION, FULLVERSION, DIAGS, HELP, A, X, J, MOREINFO, WERROR, COMPLEXINFERENCE,
    PROMPT, DOE, PRINTSOURCE, WARNUNCHECKED, XMAXERRS, XMAXWARNS, XSTDOUT, XPKGINFO,
    XPRINT, XPRINTROUNDS, XPRINTPROCESSORINFO, XPREFER, O, XJCOV, XD, AT, SOURCEFILE;

    public String optionName;
    public boolean hasArg() { return false; }
    public boolean matches(String s) { return false; }
}
