package com.sun.source.tree;

public interface Tree {
    Kind getKind();
    <R,D> R accept(TreeVisitor<R,D> visitor, D data);

    public enum Kind {
        ANNOTATED_TYPE, ANNOTATION, ANNOTATION_TYPE, ARRAY_ACCESS, ARRAY_TYPE,
        ASSERT, ASSIGNMENT, BLOCK, BREAK, CASE, CATCH, CLASS, COMPILATION_UNIT,
        CONDITIONAL_EXPRESSION, CONTINUE, DO_WHILE_LOOP, EMPTY_STATEMENT,
        ENHANCED_FOR_LOOP, ERRONEOUS, EXPRESSION_STATEMENT, FOR_LOOP, IDENTIFIER,
        IF, IMPORT, INSTANCE_OF, INTERSECTION_TYPE, LABELED_STATEMENT, LAMBDA_EXPRESSION,
        MEMBER_REFERENCE, MEMBER_SELECT, METHOD, METHOD_INVOCATION, MODIFIERS,
        NEW_ARRAY, NEW_CLASS, OTHER, PARAMETERIZED_TYPE, PARENTHESIZED, PRIMITIVE_TYPE,
        RETURN, SWITCH, SYNCHRONIZED, THROW, TRY, TYPE_CAST, TYPE_PARAMETER, UNION_TYPE,
        VARIABLE, WHILE_LOOP, WILDCARD,
        // Operators
        POSTFIX_INCREMENT, POSTFIX_DECREMENT, PREFIX_INCREMENT, PREFIX_DECREMENT,
        UNARY_PLUS, UNARY_MINUS, BITWISE_COMPLEMENT, LOGICAL_COMPLEMENT,
        MULTIPLY, DIVIDE, REMAINDER, PLUS, MINUS, LEFT_SHIFT, RIGHT_SHIFT,
        UNSIGNED_RIGHT_SHIFT, LESS_THAN, GREATER_THAN, LESS_THAN_EQUAL,
        GREATER_THAN_EQUAL, EQUAL_TO, NOT_EQUAL_TO, AND, XOR, OR,
        CONDITIONAL_AND, CONDITIONAL_OR, MULTIPLY_ASSIGNMENT, DIVIDE_ASSIGNMENT,
        REMAINDER_ASSIGNMENT, PLUS_ASSIGNMENT, MINUS_ASSIGNMENT, LEFT_SHIFT_ASSIGNMENT,
        RIGHT_SHIFT_ASSIGNMENT, UNSIGNED_RIGHT_SHIFT_ASSIGNMENT, AND_ASSIGNMENT,
        XOR_ASSIGNMENT, OR_ASSIGNMENT,
        // Literals
        INT_LITERAL, LONG_LITERAL, FLOAT_LITERAL, DOUBLE_LITERAL, BOOLEAN_LITERAL,
        CHAR_LITERAL, STRING_LITERAL, NULL_LITERAL
    }
}
