

 IBM Research Jikes Parser Generator    1.2 Wed Nov 26 17:22:10 2025       Page 1

%OPTIONS la=1,default=5,table,goto-default
***ERROR: "la1" is an invalid option
***ERROR: "goto-defaullt" is an invalid option

Options in effect:
    NOACTION  ACTFILE-NAME=test-act.h  BLOCKB=/.  BLOCKE=./  BYTE  CONFLICTS  
    DEFAULT=5  NODEBUG  NODEFERRED  NOEDIT  NOERROR-MAPS  ESCAPE=%  
    FILE-PREFIX=test-  NOFIRST  NOFOLLOW  NOGENERATE-PARSER  GOTO-DEFAULT  
    HACTFILE-NAME=test-hdr.h  HBLOCKB=/:  HBLOCKE=:/  LALR=1  NOLIST  
    MAX-DISTANCE=30  MIN-DISTANCE=3  NAMES=OPTIMIZED  NONT-CHECK  ORMARK=|  
    OUTPUT-SIZE=80  PREFIX=  READ-REDUCE  NOSCOPES  NOSHIFT-DEFAULT  
    NOSINGLE-PRODUCTIONS  STACK-SIZE=128  NOSTATES  SUFFIX=  TABLE=SPACE  
    TRACE=CONFLICTS  NOVERBOSE  WARNINGS  NOXREF  



 IBM Research Jikes Parser Generator    1.2 Wed Nov 26 17:22:10 2025       Page 2

*** The following Terminals are useless: 


        MINUS  ERROR  


This grammar is LALR(1).


 IBM Research Jikes Parser Generator    1.2 Wed Nov 26 17:22:10 2025       Page 3


Number of Terminals: 5
Number of Nonterminals: 2
Number of Productions: 4
Number of Items: 10
Number of States: 4
Number of Shift actions: 1
Number of Goto actions: 2
Number of Shift/Reduce actions: 2
Number of Goto/Reduce actions: 0
Number of Reduce actions: 2
Number of Shift-Reduce conflicts: 0
Number of Reduce-Reduce conflicts: 0
Number of Goto entries saved by default: 2
Number of Goto/Reduce entries saved by default: 0
Number of non-terminals eliminated: 3
Length of base Check Table: 7
Length of base Action Table: 4
Number of entries in base Action Table: 4
Percentage of increase: 0.0%
Storage required for base Tables: 21 Bytes, 1K
Storage required for Rules: 6 Bytes
Number of unique terminal states: 4
Number of Shift actions saved by merging: 0
Number of Reduce actions saved by merging: 0
Number of Reduce saved by default: 1
Length of Terminal Check Table: 13
Length of Terminal Action Table: 9
Number of entries in Terminal Action Table: 8
Percentage of increase: 12.5%
Storage required for Terminal Tables: 31 Bytes, 1K
Total storage required for Tables: 52 Bytes, 1K


Actions in Compressed Tables:
     Number of Shifts: 1
     Number of Shift/Reduces: 2
     Number of Gotos: 0
     Number of Goto/Reduces: 0
     Number of Reduces: 1
     Number of Defaults: 1
