#!/usr/bin/env python3
"""
Post-process jikespg output to add Jopa namespace and fix formatting.
"""

import sys
import os
import re

def process_file(input_path, output_path, file_type):
    """Process a single generated file."""
    with open(input_path, 'r') as f:
        content = f.read()

    # Get the base name for include guards
    basename = os.path.basename(output_path).replace('.', '_').upper()

    # Replace include guards with #pragma once and add namespace
    # Remove old include guard pattern
    content = re.sub(r'#ifndef \w+_INCLUDED\s*\n#define \w+_INCLUDED\s*\n', '', content)
    content = re.sub(r'#endif /\* \w+_INCLUDED \*/', '', content)
    content = content.strip()

    # jikespg now generates all constants with error-maps option

    # Fix unused parameter warning in javaprs.h
    if file_type == "prs":
        content = content.replace("LexStream *stream", "LexStream *")

    # Add Java 8 tokens for javasym.h (scanner needs these even without grammar rules)
    if file_type == "sym":
        # Find the last token and add Java 8 tokens after it
        java8_tokens = """,
      // Java 8 tokens (scanner recognizes but parser tables don't have grammar rules)
      TK_ARROW = 112,        // -> for lambdas
      TK_COLON_COLON = 113   // :: for method references"""
        # Replace the closing }; with the extra tokens + };
        content = re.sub(r'\n\s*\};', java8_tokens + '\n     };', content)

    # Build the output
    output = f"""// Generated by jikespg - DO NOT EDIT
// Regenerate using: cmake --build build --target generate_parser

#pragma once

namespace Jopa {{ // Open namespace Jopa block

{content}

}} // Close namespace Jopa block
"""

    with open(output_path, 'w') as f:
        f.write(output)

def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <input_dir> <output_dir> <prefix>")
        sys.exit(1)

    input_dir = sys.argv[1]
    output_dir = sys.argv[2]
    prefix = sys.argv[3]

    os.makedirs(output_dir, exist_ok=True)

    files = [
        (f"{prefix}dcl.h", f"{prefix}dcl.h", "dcl"),
        (f"{prefix}def.h", f"{prefix}def.h", "def"),
        (f"{prefix}prs.h", f"{prefix}prs.h", "prs"),
        (f"{prefix}sym.h", f"{prefix}sym.h", "sym"),
    ]

    for src_name, dst_name, file_type in files:
        src_path = os.path.join(input_dir, src_name)
        dst_path = os.path.join(output_dir, dst_name)
        if os.path.exists(src_path):
            process_file(src_path, dst_path, file_type)
            print(f"Processed: {src_name} -> {dst_name}")
        else:
            print(f"Warning: {src_path} not found")

if __name__ == "__main__":
    main()
